version: "2"
services:
  namenode:
    image: apache/hadoop:3
    hostname: namenode
    container_name: hadoop_namenode
    command: ["hdfs", "namenode"]
    ports:
      - "9870:9870"
    env_file:
      - ./hadoop.env
    environment:
      ENSURE_NAMENODE_DIR: "/tmp/hadoop-root/dfs/name"

  datanode_1:
    image: apache/hadoop:3
    container_name: hadoop_datanode_1
    command: ["hdfs", "datanode"]
    ports:
      - "9863:9863"
    env_file:
      - ./hadoop.env
      
  datanode_2:
    image: apache/hadoop:3
    container_name: hadoop_datanode_2
    command: ["hdfs", "datanode"]
    ports:
      - "9864:9864"
    env_file:
      - ./hadoop_2.env

  datanode_3:
    image: apache/hadoop:3
    container_name: hadoop_datanode_3
    command: ["hdfs", "datanode"]
    ports:
      - "9865:9865"
    env_file:
      - ./hadoop_3.env

  resourcemanager:
    image: apache/hadoop:3
    hostname: resourcemanager
    command: ["yarn", "resourcemanager"]
    ports:
        - 8088:8088
    env_file:
      - ./hadoop.env

  nodemanager:
    image: apache/hadoop:3
    command: ["yarn", "nodemanager"]
    env_file:
      - ./hadoop.env
